input:
  path: /app/watch
  extension: .aax
  cleanup: true

output:
  path: /app/output
  extension: .m4b
  overwrite: false

ffmpeg:
  run: true
  path: ffmpeg
  additional_args:
    - -hide_banner
    - -loglevel
    - error
    - -nostats
    - -y

ffprobe:
  path: ffprobe
  additional_args:
    - -show_entries 
    - format_tags=title 
    - -of 
    - compact=p=0 
    - -v 
    - "0"

logging:
  level: info
  format: '%(asctime)s - %(levelname)s - [%(name)s] %(message)s'
